// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiMxv5sKt3lLrUoD3cTtICqAFdJ6NUhYk',
    appId: '1:30477460615:android:dfb5480d9f68625aa24422',
    messagingSenderId: '30477460615',
    projectId: 'eacx-5ab0e',
    storageBucket: 'eacx-5ab0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh7KVUccwmJbhO1lU3XjW8XRdAJrVN6_s',
    appId: '1:30477460615:ios:9ffd8b7c8bac9625a24422',
    messagingSenderId: '30477460615',
    projectId: 'eacx-5ab0e',
    storageBucket: 'eacx-5ab0e.firebasestorage.app',
    iosClientId: '30477460615-e5p820an5507o0fajf5f3o3cfbrqiqq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.itx',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGsc_oMK93Jb82MkwB3aMXGXcWKNU-4mc',
    appId: '1:30477460615:web:d8a5c244e748a4dea24422',
    messagingSenderId: '30477460615',
    projectId: 'eacx-5ab0e',
    authDomain: 'eacx-5ab0e.firebaseapp.com',
    storageBucket: 'eacx-5ab0e.firebasestorage.app',
    measurementId: 'G-KKW078HJD0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh7KVUccwmJbhO1lU3XjW8XRdAJrVN6_s',
    appId: '1:30477460615:ios:9ffd8b7c8bac9625a24422',
    messagingSenderId: '30477460615',
    projectId: 'eacx-5ab0e',
    storageBucket: 'eacx-5ab0e.firebasestorage.app',
    iosClientId: '30477460615-e5p820an5507o0fajf5f3o3cfbrqiqq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.itx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGsc_oMK93Jb82MkwB3aMXGXcWKNU-4mc',
    appId: '1:30477460615:web:50dfe8c761a7ed43a24422',
    messagingSenderId: '30477460615',
    projectId: 'eacx-5ab0e',
    authDomain: 'eacx-5ab0e.firebaseapp.com',
    storageBucket: 'eacx-5ab0e.firebasestorage.app',
    measurementId: 'G-63LPNYXXMF',
  );

}